[auth]
password = "ElaTeamMetrics2025!"

[redshift]
host = "redshift.revolutionprep.com"
port = 5439
database = "rp_admin"
user = "tharrington"
password = "PlVKrvT6X9iHIDoL"


[rp_db]
host     = "replica.revolutionprep.com"
port     = 3306
user     = "tyler.harrington"
password = '1vm7243fnh8ic648'
